# Generated by Django 5.1.4 on 2025-01-12 16:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControleDeRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_prevista_recebimento', models.DateField()),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Recebido', 'Recebido'), ('Não Recebido', 'Não Recebido'), ('Atrasado', 'Atrasado')], default='Não Recebido', max_length=20)),
                ('numero_extrato', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField()),
                ('porcentagem_parcela', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operadora', models.CharField(max_length=255)),
                ('comissionamento_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo', models.CharField(choices=[('PME', 'PME'), ('PF', 'Pessoa Física'), ('Adesão', 'Adesão')], max_length=50)),
                ('numero_parcelas', models.PositiveIntegerField()),
                ('taxa_plano_valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('taxa_plano_tipo', models.CharField(choices=[('Valor Fixo', 'Valor Fixo'), ('Porcentagem', 'Porcentagem')], default='Valor Fixo', max_length=20)),
            ],
            options={
                'unique_together': {('operadora', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_proposta', models.CharField(max_length=100, unique=True)),
                ('valor_plano', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_consultor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_venda', models.DateField(default=django.utils.timezone.now)),
                ('data_vigencia', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consultor')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plano')),
            ],
        ),
        migrations.DeleteModel(
            name='SeuModelo',
        ),
        migrations.AddField(
            model_name='controlederecebimento',
            name='parcela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parcela'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plano'),
        ),
        migrations.AddField(
            model_name='controlederecebimento',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.venda'),
        ),
    ]
