# Generated by Django 5.1.4 on 2025-02-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cliente_consultor_controlederecebimento_parcela_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='cliente',
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente_documento',
            field=models.CharField(default='', max_length=50, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente_nome',
            field=models.CharField(default=12345678999, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente_telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
