# Generated by Django 5.1.4 on 2025-02-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_venda_cliente_venda_cliente_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='tipo',
            field=models.CharField(choices=[('PME', 'PME'), ('PF', 'Pessoa Física'), ('Adesão', 'Adesão'), ('PF (Odonto)', 'PF (Odonto)'), ('PME (Odonto)', 'PME (Odonto)')], max_length=50),
        ),
    ]
