# Generated by Django 5.1.4 on 2025-02-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_plano_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='canal_entrada',
            field=models.CharField(choices=[('Indicação', 'Indicação'), ('Portifolio', 'Portifolio'), ('Comprado', 'Comprado'), ('Rede Social', 'Rede Social'), ('Site', 'Site'), ('Parceria', 'Parceria')], default='Indicação', max_length=50),
        ),
    ]
